-   id: eslint
    name: eslint
    entry: eslint
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    pass_filenames: false
    additional_dependencies: ["eslint@7.13.0"]
